# Instance parameters for rtsp-camera.
# Run: ./target/release/rtsp_camera_node -c configs/terrace.yaml

name: tapo_terrace
publish_topic: camera/tapo_terrace/compressed
url: "rtsp://tapo_terrace:clawd2026@192.168.1.151:554/stream1"
latency: 50
frame_rate: 10
